server:
  port: 9999
spring:
  jackson:
    time-zone: GMT+8  #市区设置
  application:
    name: his
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.31.6:3306/hanggou_goods?serverTimezone=UTC&useSSL=false&autoReconnect=true
    url: jdbc:mysql://127.0.0.1:3306/his?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 1319032541


